### ISSUE TITLE
Include fails when done from hooks

### ISSUE THREAD

**Issue by vshalts** [debops/debops-tools#153]
Hi,

I want to split functionality used in hooks into several files (hook called from debops.users). For that I would like to use include from hook.
But it doesn't work this way. I extracted smallest possible example to reproduce problem: https://www.dropbox.com/s/fjc1m2n6qwtkqbs/debops-test.zip?dl=0

Short description (in case it will be problems with download):
Have two playbooks (test_fail, test_success) and hook spitted into two files (post_main, prezto).

First (test_fail) done the way it is used in all DebOps playbooks  will not print Success message - fail. Second (test_success) work fine, but I don't understand why and unfortunately it is not how it done in debops, so I can't use it. Can you please give any suggestion about why first case fail and how can I split playbook called from debops hook? Thanks!

test_fail.yml:

``` yml

---

- hosts: localhost
  tasks:
    - name: DebOps post_tasks hook
      include: "{{ lookup('task_src', 'users/post_main.yml') }}"
```

test_success.yml:

``` yml

---

- hosts: localhost
  tasks:
    - name: DebOps post_tasks hook
      include: "{{ p_path }}"
  vars:
    p_path: "{{ lookup('task_src', 'users/post_main.yml')}}"
```

post_main.yml:

``` yml

---

- name: Debug
  debug: msg="{{ lookup('task_src', 'users/prezto.yml') }}"

- name: prezto
  include: "{{ lookup('task_src', 'users/prezto.yml') }}"
```

prezto.yml:

``` yml

---

- debug: msg="Success"
```
